import express from 'express';
import { db, getAdminPasswordHash, setAdminPasswordHash, getSettings, setSettings, audit } from './db.js';
import { encryptSecret, verifyPassword, hashPassword, createSessionToken, randomToken, cookieOptions, parseCookies, verifySessionToken } from './security.js';
import { requireAuth, requireCsrf } from './auth.js';
import { ssh } from './ssh.js';
import { getLiveState, getAllLiveStates, pollServerNow } from './monitor.js';
import { listActiveAlerts } from './alerts.js';
import { getMarketState, refreshXmrUsd } from './market.js';
import { applyMiningConfig, restartXmrig, setHugePages, setMsr, getXmrigLog, getP2poolLog, getMonerodLog, runCommand, bootstrapServer, performanceProfiles, applyPerformanceProfile, autoFixServer, rollingRestart, rollingUpdateXmrig } from './operations.js';
import { discoverServer, getDiscovery } from './discovery.js';
import { refreshUpdates, versionStatus } from './updates.js';
import { createJob, runJob, getJob, listJobs } from './jobs.js';

export const api = express.Router();
const loginAttempts = new Map();

function ip(req) { return req.ip || req.socket.remoteAddress || ''; }
function cleanHost(v) { const s=String(v||'').trim();if(!s||s.length>253||/[\s\0/]/.test(s))throw new Error('Некорректный host');return s; }
function cleanUsername(v) { const s=String(v||'').trim();if(!s||s.length>64||/[\s\0]/.test(s))throw new Error('Некорректный логин');return s; }
function cleanPath(v,fallback) { const s=String(v||fallback).trim();if(!s.startsWith('/')||/[\r\n\0]/.test(s)||s.length>500)throw new Error('Путь должен быть абсолютным');return s; }
function cleanService(v,fallback) { const s=String(v||fallback).trim();if(!/^[A-Za-z0-9_.@-]+$/.test(s))throw new Error('Некорректное имя systemd-сервиса');return s; }
function cleanIcon(v){const s=String(v||'🖥️').trim();return s.slice(0,16)||'🖥️';}
function asBool(v) { return v === true || ['1','true','yes','on'].includes(String(v).toLowerCase()); }
function encryptedOrKeep(raw, old) { if (raw === undefined || raw === null || raw === '') return old || null; return encryptSecret(String(raw)); }
function parseDiscovery(row){return getDiscovery(row);}
function sparkline(id){return db.prepare('SELECT ts,hash_60s AS hash60s,temp_c AS tempC FROM metrics WHERE server_id=? AND hash_60s IS NOT NULL ORDER BY ts DESC LIMIT 36').all(id).reverse();}
function serverDto(row,{withSpark=false}={}) {
  if (!row) return null;
  return {
    id:row.id,name:row.name,icon:row.icon||'🖥️',host:row.host,port:row.port,username:row.username,authType:row.auth_type,hostFingerprint:row.host_fingerprint||'',
    xmrigApiPort:row.xmrig_api_port,xmrigConfigPath:row.xmrig_config_path,xmrigService:row.xmrig_service,p2poolService:row.p2pool_service,p2poolLogPath:row.p2pool_log_path,
    monerodService:row.monerod_service||'monerod',monerodRpcPort:row.monerod_rpc_port||18081,monerodLogPath:row.monerod_log_path||'/var/log/monero/monero.log',performanceProfile:row.performance_profile||'maximum',
    enabled:Boolean(row.enabled),tags:row.tags||'',hashMin:row.hash_min,tempMax:row.temp_max,status:row.status,lastSeenAt:row.last_seen_at,lastError:row.last_error||'',
    hasPassword:Boolean(row.password_enc),hasPrivateKey:Boolean(row.private_key_enc),hasSudoPassword:Boolean(row.sudo_password_enc),hasApiToken:Boolean(row.xmrig_api_token_enc),
    createdAt:row.created_at,updatedAt:row.updated_at,discovery:parseDiscovery(row),live:getLiveState(row.id),...(withSpark?{sparkline:sparkline(row.id)}:{})
  };
}

api.post('/auth/login',(req,res)=>{const clientIp=ip(req);const a=loginAttempts.get(clientIp)||{count:0,reset:Date.now()+600000};if(Date.now()>a.reset){a.count=0;a.reset=Date.now()+600000;}if(a.count>=8)return res.status(429).json({error:'Слишком много попыток входа'});if(!verifyPassword(req.body?.password||'',getAdminPasswordHash())){a.count++;loginAttempts.set(clientIp,a);audit({ip:clientIp,action:'login',status:'error',details:'invalid password'});return res.status(401).json({error:'Неверный пароль'});}loginAttempts.delete(clientIp);const csrf=randomToken();res.cookie('panel_session',createSessionToken(),cookieOptions({httpOnly:true}));res.cookie('panel_csrf',csrf,cookieOptions({httpOnly:false}));audit({ip:clientIp,action:'login'});res.json({ok:true,csrf});});
api.post('/auth/logout',requireAuth,requireCsrf,(req,res)=>{res.clearCookie('panel_session',{path:'/'});res.clearCookie('panel_csrf',{path:'/'});audit({ip:ip(req),action:'logout'});res.json({ok:true});});
api.get('/auth/me',(req,res)=>{const c=parseCookies(req.headers.cookie||'');res.json({authenticated:verifySessionToken(c.panel_session),csrf:c.panel_csrf||''});});
api.use(requireAuth);api.use(requireCsrf);

api.get('/overview',(req,res)=>{const servers=db.prepare('SELECT * FROM servers ORDER BY name COLLATE NOCASE').all().map(r=>serverDto(r,{withSpark:true}));const online=servers.filter(s=>['online','starting'].includes(s.live?.status)).length;const totalHash=servers.reduce((n,s)=>n+(Number(s.live?.hash60s)||0),0);const temps=servers.map(s=>s.live?.tempC).filter(Number.isFinite);res.json({servers,live:getAllLiveStates(),summary:{total:servers.length,online,totalHash,maxTemp:temps.length?Math.max(...temps):null},alerts:listActiveAlerts(),market:getMarketState(),jobs:listJobs(5)});});
api.get('/history/farm',(req,res)=>{const hours=Math.max(1,Math.min(24*30,Number(req.query.hours)||24));const bucket=hours<=6?60000:hours<=48?300000:3600000;const rows=db.prepare(`SELECT CAST(ts/? AS INTEGER)*? AS ts,SUM(hash_60s) AS hash60s,MAX(temp_c) AS maxTemp FROM metrics WHERE ts>=? AND hash_60s IS NOT NULL GROUP BY CAST(ts/? AS INTEGER) ORDER BY ts`).all(bucket,bucket,Date.now()-hours*3600000,bucket);res.json(rows);});

api.get('/servers',(req,res)=>res.json(db.prepare('SELECT * FROM servers ORDER BY name COLLATE NOCASE').all().map(r=>serverDto(r,{withSpark:true}))));
api.get('/servers/:id',(req,res)=>{const row=db.prepare('SELECT * FROM servers WHERE id=?').get(Number(req.params.id));if(!row)return res.status(404).json({error:'Сервер не найден'});res.json(serverDto(row,{withSpark:true}));});

api.post('/servers/test',async(req,res)=>{const b=req.body||{};let temp=null;try{temp={id:0,host:cleanHost(b.host),port:Math.max(1,Math.min(65535,Number(b.port)||22)),username:cleanUsername(b.username),auth_type:['agent','password','key'].includes(b.authType)?b.authType:'password',password_enc:b.password?encryptSecret(b.password):null,private_key_enc:b.privateKey?encryptSecret(b.privateKey):null,private_key_passphrase_enc:b.privateKeyPassphrase?encryptSecret(b.privateKeyPassphrase):null,host_fingerprint:null};const out=await ssh.testConnection(temp,{timeoutMs:12000});const lines=[`SSH: ${out.ok?'OK':'ошибка'}`,`Хост: ${temp.username}@${temp.host}:${temp.port}`,`Авторизация: ${temp.auth_type}`,out.hostFingerprint?`Host key SHA256: ${out.hostFingerprint}`:'',out.stdout||'',out.stderr?`[stderr] ${out.stderr}`:''].filter(Boolean);audit({ip:ip(req),action:'ssh-test',status:out.ok?'ok':'error',details:`${temp.username}@${temp.host}:${temp.port}`});res.json({ok:out.ok,output:lines.join('\n'),error:out.ok?'':out.stderr||'SSH-команда не выполнена'});}catch(e){audit({ip:ip(req),action:'ssh-test',status:'error',details:e.message});res.json({ok:false,output:'',error:e.message||'Ошибка SSH'});}});

api.post('/servers',async(req,res,next)=>{try{const b=req.body||{},now=Date.now(),authType=['agent','password','key'].includes(b.authType)?b.authType:'agent',defaultProfile=getSettings().performance_profile_default||'maximum';const transient={id:0,host:cleanHost(b.host),port:Math.max(1,Math.min(65535,Number(b.port)||22)),username:cleanUsername(b.username),auth_type:authType,password_enc:b.password?encryptSecret(b.password):null,private_key_enc:b.privateKey?encryptSecret(b.privateKey):null,private_key_passphrase_enc:b.privateKeyPassphrase?encryptSecret(b.privateKeyPassphrase):null,host_fingerprint:null};if(b.testConnection!==false){const t=await ssh.testConnection(transient,{timeoutMs:12000});if(!t.ok)throw new Error(`SSH connection test failed: ${t.stderr||'no response'}`);}const info=db.prepare(`INSERT INTO servers(name,icon,host,port,username,auth_type,password_enc,private_key_enc,private_key_passphrase_enc,sudo_password_enc,xmrig_api_token_enc,xmrig_api_port,xmrig_config_path,xmrig_service,p2pool_service,p2pool_log_path,monerod_service,monerod_rpc_port,monerod_log_path,performance_profile,enabled,tags,hash_min,temp_max,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(String(b.name||b.host||'Miner').slice(0,100),cleanIcon(b.icon),cleanHost(b.host),Math.max(1,Math.min(65535,Number(b.port)||22)),cleanUsername(b.username),authType,b.password?encryptSecret(b.password):null,b.privateKey?encryptSecret(b.privateKey):null,b.privateKeyPassphrase?encryptSecret(b.privateKeyPassphrase):null,b.sudoPassword?encryptSecret(b.sudoPassword):null,b.xmrigApiToken?encryptSecret(b.xmrigApiToken):null,Math.max(1,Math.min(65535,Number(b.xmrigApiPort)||60050)),cleanPath(b.xmrigConfigPath,'/opt/xmrig/config.json'),cleanService(b.xmrigService,'xmrig'),cleanService(b.p2poolService,'p2pool'),cleanPath(b.p2poolLogPath,'/var/log/p2pool.log'),cleanService(b.monerodService,'monerod'),Math.max(1,Math.min(65535,Number(b.monerodRpcPort)||18081)),cleanPath(b.monerodLogPath,`/home/${cleanUsername(b.username)}/.bitmonero/bitmonero.log`),performanceProfiles[b.performanceProfile]?b.performanceProfile:(performanceProfiles[defaultProfile]?defaultProfile:'maximum'),b.enabled===false?0:1,String(b.tags||'').slice(0,300),b.hashMin?Number(b.hashMin):null,b.tempMax?Number(b.tempMax):null,now,now);const row=db.prepare('SELECT * FROM servers WHERE id=?').get(info.lastInsertRowid);audit({ip:ip(req),serverId:row.id,action:'server-add',details:`${row.username}@${row.host}:${row.port}`});discoverServer(row.id,{apply:true,actorIp:ip(req)}).then(()=>pollServerNow(row.id)).catch(()=>pollServerNow(row.id).catch(()=>{}));res.status(201).json(serverDto(row));}catch(e){next(e);}});

api.put('/servers/:id',(req,res,next)=>{try{const id=Number(req.params.id),old=db.prepare('SELECT * FROM servers WHERE id=?').get(id);if(!old)return res.status(404).json({error:'Сервер не найден'});const b=req.body||{};db.prepare(`UPDATE servers SET name=?,icon=?,host=?,port=?,username=?,auth_type=?,password_enc=?,private_key_enc=?,private_key_passphrase_enc=?,sudo_password_enc=?,xmrig_api_token_enc=?,xmrig_api_port=?,xmrig_config_path=?,xmrig_service=?,p2pool_service=?,p2pool_log_path=?,monerod_service=?,monerod_rpc_port=?,monerod_log_path=?,performance_profile=?,enabled=?,tags=?,hash_min=?,temp_max=?,updated_at=? WHERE id=?`).run(String(b.name??old.name).slice(0,100),cleanIcon(b.icon??old.icon),cleanHost(b.host??old.host),Math.max(1,Math.min(65535,Number(b.port??old.port))),cleanUsername(b.username??old.username),['agent','password','key'].includes(b.authType)?b.authType:old.auth_type,encryptedOrKeep(b.password,old.password_enc),encryptedOrKeep(b.privateKey,old.private_key_enc),encryptedOrKeep(b.privateKeyPassphrase,old.private_key_passphrase_enc),encryptedOrKeep(b.sudoPassword,old.sudo_password_enc),encryptedOrKeep(b.xmrigApiToken,old.xmrig_api_token_enc),Math.max(1,Math.min(65535,Number(b.xmrigApiPort??old.xmrig_api_port))),cleanPath(b.xmrigConfigPath??old.xmrig_config_path,old.xmrig_config_path),cleanService(b.xmrigService??old.xmrig_service,old.xmrig_service),cleanService(b.p2poolService??old.p2pool_service,old.p2pool_service),cleanPath(b.p2poolLogPath??old.p2pool_log_path,old.p2pool_log_path),cleanService(b.monerodService??old.monerod_service,old.monerod_service||'monerod'),Math.max(1,Math.min(65535,Number(b.monerodRpcPort ?? old.monerod_rpc_port ?? 18081))),cleanPath(b.monerodLogPath??old.monerod_log_path,old.monerod_log_path||`/home/${old.username}/.bitmonero/bitmonero.log`),performanceProfiles[b.performanceProfile]?b.performanceProfile:old.performance_profile,b.enabled===undefined?old.enabled:(asBool(b.enabled)?1:0),String(b.tags??old.tags).slice(0,300),b.hashMin===''?null:(b.hashMin??old.hash_min),b.tempMax===''?null:(b.tempMax??old.temp_max),Date.now(),id);if(b.resetHostFingerprint)db.prepare('UPDATE servers SET host_fingerprint=NULL WHERE id=?').run(id);ssh.invalidate(id);audit({ip:ip(req),serverId:id,action:'server-update'});res.json(serverDto(db.prepare('SELECT * FROM servers WHERE id=?').get(id)));}catch(e){next(e);}});
api.delete('/servers/:id',(req,res)=>{const id=Number(req.params.id),row=db.prepare('SELECT * FROM servers WHERE id=?').get(id);if(!row)return res.status(404).json({error:'Сервер не найден'});ssh.invalidate(id);db.prepare('DELETE FROM servers WHERE id=?').run(id);audit({ip:ip(req),action:'server-delete',details:`${row.name} (${row.host})`});res.json({ok:true});});

api.post('/servers/:id/poll',async(req,res,next)=>{try{res.json(await pollServerNow(req.params.id));}catch(e){next(e);}});
api.post('/servers/:id/discover',async(req,res,next)=>{try{res.json(await discoverServer(req.params.id,{apply:true,actorIp:ip(req)}));}catch(e){next(e);}});
api.get('/servers/:id/history',(req,res)=>{const id=Number(req.params.id),hours=Math.max(1,Math.min(24*30,Number(req.query.hours)||24));res.json(db.prepare(`SELECT ts,hash_10s AS hash10s,hash_60s AS hash60s,hash_15m AS hash15m,temp_c AS tempC,accepted,rejected,uptime,version,pool,p2pool_status AS p2poolStatus,error_count AS errorCount,cpu_mhz AS cpuMHz,load_1 AS load1,load_5 AS load5,load_15 AS load15,hugepages_total AS hugePagesTotal,hugepages_free AS hugePagesFree,hugepages_1g_total AS hugePages1gTotal,hugepages_1g_free AS hugePages1gFree,msr_status AS msrStatus,xmrig_status AS xmrigStatus,monerod_status AS monerodStatus,monero_height AS moneroHeight,monero_target_height AS moneroTargetHeight,network_status AS networkStatus,baseline_hash AS baselineHash FROM metrics WHERE server_id=? AND ts>=? ORDER BY ts ASC LIMIT 50000`).all(id,Date.now()-hours*3600000));});
api.get('/servers/:id/logs/xmrig',async(req,res,next)=>{try{res.type('text/plain').send(await getXmrigLog(req.params.id,req.query.lines));}catch(e){next(e);}});
api.get('/servers/:id/logs/p2pool',async(req,res,next)=>{try{res.type('text/plain').send(await getP2poolLog(req.params.id,req.query.lines));}catch(e){next(e);}});
api.get('/servers/:id/logs/monerod',async(req,res,next)=>{try{res.type('text/plain').send(await getMonerodLog(req.params.id,req.query.lines));}catch(e){next(e);}});
api.post('/servers/:id/actions/restart',async(req,res,next)=>{try{res.json(await restartXmrig(req.params.id,{actorIp:ip(req)}));}catch(e){next(e);}});
api.post('/servers/:id/actions/apply-config',async(req,res,next)=>{try{res.json(await applyMiningConfig(req.params.id,{actorIp:ip(req)}));}catch(e){next(e);}});
api.post('/servers/:id/actions/profile',async(req,res,next)=>{try{res.json(await applyPerformanceProfile(req.params.id,req.body?.profile,{actorIp:ip(req)}));}catch(e){next(e);}});
api.post('/servers/:id/actions/auto-fix',async(req,res,next)=>{try{res.json(await autoFixServer(req.params.id,{actorIp:ip(req)}));}catch(e){next(e);}});
api.post('/servers/:id/actions/hugepages',async(req,res,next)=>{try{res.json(await setHugePages(req.params.id,{...req.body,actorIp:ip(req)}));}catch(e){next(e);}});
api.post('/servers/:id/actions/msr',async(req,res,next)=>{try{res.json(await setMsr(req.params.id,{enabled:asBool(req.body?.enabled),actorIp:ip(req)}));}catch(e){next(e);}});
api.post('/servers/:id/actions/command',async(req,res,next)=>{try{res.json(await runCommand(req.params.id,req.body?.command,{actorIp:ip(req)}));}catch(e){next(e);}});
api.post('/servers/:id/actions/bootstrap',async(req,res,next)=>{try{res.json(await bootstrapServer(req.params.id,req.body||{},{actorIp:ip(req)}));}catch(e){next(e);}});
api.get('/profiles',(req,res)=>res.json(Object.values(performanceProfiles)));

api.post('/fleet/actions/rolling-restart',(req,res)=>{const ids=Array.isArray(req.body?.serverIds)?req.body.serverIds:db.prepare('SELECT id FROM servers WHERE enabled=1 ORDER BY id').all().map(x=>x.id);const job=createJob('rolling-restart','Rolling restart XMRig');runJob(job,async update=>rollingRestart(ids,{actorIp:ip(req),progress:update}));audit({ip:ip(req),action:'rolling-restart-start',details:{ids}});res.status(202).json(job);});
api.post('/fleet/actions/rolling-update',(req,res)=>{const ids=Array.isArray(req.body?.serverIds)?req.body.serverIds:db.prepare('SELECT id FROM servers WHERE enabled=1 ORDER BY id').all().map(x=>x.id);const version=String(req.body?.version||'');if(!/^\d+\.\d+\.\d+$/.test(version))return res.status(400).json({error:'Некорректная версия XMRig'});const job=createJob('rolling-update',`Rolling update XMRig ${version}`);runJob(job,async update=>rollingUpdateXmrig(ids,version,{actorIp:ip(req),progress:update}));audit({ip:ip(req),action:'rolling-update-start',details:{ids,version}});res.status(202).json(job);});
api.get('/jobs',(req,res)=>res.json(listJobs(req.query.limit)));
api.get('/jobs/:id',(req,res)=>{const j=getJob(req.params.id);if(!j)return res.status(404).json({error:'Задача не найдена'});res.json(j);});

api.get('/updates',async(req,res)=>{const u=await refreshUpdates({force:asBool(req.query.force)});const servers=db.prepare('SELECT * FROM servers ORDER BY name').all().map(r=>{const dto=serverDto(r);const installed=dto.live?.version||dto.discovery?.xmrig?.version||'';return{id:dto.id,name:dto.name,icon:dto.icon,installedXmrig:installed,xmrigStatus:u.data?.xmrig?versionStatus(installed,u.data.xmrig.version):'unknown',p2poolVersion:dto.discovery?.p2pool?.version||'',monerodVersion:dto.discovery?.monerod?.version||''};});res.json({...u,servers});});
api.get('/market/xmr-usd',(req,res)=>res.json(getMarketState()));api.post('/market/xmr-usd/refresh',async(req,res)=>res.json(await refreshXmrUsd({force:true})));

api.get('/settings',(req,res)=>res.json(getSettings()));
api.put('/settings',async(req,res,next)=>{try{const b=req.body||{};const allowed=new Set(['wallet','pool_url','pool_pass','pool_tls','xmrig_version','temp_warn','temp_critical','hash_drop_percent','offline_after_seconds','alert_cooldown_seconds','history_retention_days','auto_apply_config','huge_pages_enabled','huge_pages_1g','huge_pages_count','msr_enabled','telegram_enabled','telegram_chat_id','telegram_bot_token','auto_recovery_enabled','auto_recovery_failures','auto_recovery_cooldown_seconds','grace_period_seconds','baseline_window_hours','baseline_min_samples','performance_profile_default','network_check_enabled','network_check_host','updates_auto_check','update_check_hours']);const patch=Object.fromEntries(Object.entries(b.settings||b).filter(([k])=>allowed.has(k)));setSettings(patch);audit({ip:ip(req),action:'settings-update',details:Object.keys(patch).join(',')});const applyAll=asBool(b.applyAll)||(String(patch.auto_apply_config??getSettings().auto_apply_config)==='1'&&('wallet'in patch||'pool_url'in patch||'pool_pass'in patch));const applyIds=Array.isArray(b.applyServerIds)?b.applyServerIds.map(Number):(applyAll?db.prepare('SELECT id FROM servers WHERE enabled=1').all().map(x=>x.id):[]);const results=[];for(const id of [...new Set(applyIds)]){try{await applyMiningConfig(id,{actorIp:ip(req)});results.push({id,ok:true});}catch(e){results.push({id,ok:false,error:e.message});}}res.json({settings:getSettings(),applyResults:results});}catch(e){next(e);}});
api.post('/settings/password',(req,res)=>{const{currentPassword,newPassword}=req.body||{};if(!verifyPassword(currentPassword||'',getAdminPasswordHash()))return res.status(403).json({error:'Текущий пароль неверен'});if(!newPassword||String(newPassword).length<12)return res.status(400).json({error:'Новый пароль должен быть не короче 12 символов'});setAdminPasswordHash(hashPassword(newPassword));audit({ip:ip(req),action:'password-change'});res.json({ok:true});});
api.get('/alerts',(req,res)=>res.json(listActiveAlerts()));
api.get('/actions',(req,res)=>{const limit=Math.max(10,Math.min(1000,Number(req.query.limit)||200));res.json(db.prepare(`SELECT a.*,s.name AS server_name,s.host AS server_host FROM actions a LEFT JOIN servers s ON s.id=a.server_id ORDER BY a.ts DESC LIMIT ?`).all(limit));});

api.use((err,req,res,next)=>{console.error('[api]',err);audit({ip:ip(req),action:`${req.method} ${req.path}`,status:'error',details:err.message});if(String(err.message).includes('UNIQUE constraint failed'))return res.status(409).json({error:'Этот сервер уже зарегистрирован'});res.status(500).json({error:err.message||'Внутренняя ошибка'});});
