export function createServerPage(ctx) {
  const { $, $$, esc, fmtHash, fmtTemp, fmtMHz, fmtUptime, fmtDate, fmtUsd, fmtPct, helpIcon, sleep, api, toast, setHeader, navigate, openServerForm, bootstrapModal, openTerminal, bindCommonServerActions, statusBadge, compBadge, serverById, jobsPanel, Chart, hashrateScale, temperatureScale, charts, destroyCharts } = ctx;
  let overview = ctx.getOverview();
  let currentServerId = ctx.getCurrentServerId();
  let currentServerTab = ctx.getCurrentServerTab();
  const recalcSummary = () => ctx.recalcSummary();
  const loadOverview = async () => { const result = await ctx.loadOverview(); overview = ctx.getOverview(); return result; };

async function renderServer(id,tab='overview'){
  const s=await api(`/servers/${id}`);currentServerId=s.id;currentServerTab=tab;ctx.setCurrentServerState(s.id,tab);const term=`<button id="header-terminal" class="terminal-header" title="SSH-терминал">⌨ Терминал</button>`;setHeader(`<span class="title-icon">${esc(s.icon)}</span>${esc(s.name)}`,`${s.username}@${s.host}:${s.port}`,`${term}<button id="back-servers" class="ghost">← Серверы</button>`);$('#header-terminal').onclick=()=>openTerminal(s);$('#back-servers').onclick=()=>navigate('servers');
  $('#view').innerHTML=`<div class="server-tabs">${[['overview','Обзор'],['performance','Производительность'],['components','Компоненты'],['system','Система'],['logs','Логи'],['config','Управление']].map(([k,n])=>`<button class="server-tab ${tab===k?'active':''}" data-tab="${k}">${n}</button>`).join('')}</div><div id="server-tab-view"></div>`;
  $$('.server-tab').forEach(b=>b.onclick=()=>navigate('server',s.id,b.dataset.tab));
  if(tab==='performance')return renderServerPerformance(s);if(tab==='components')return renderServerComponents(s);if(tab==='system')return renderServerSystem(s);if(tab==='logs')return renderServerLogs(s);if(tab==='config')return renderServerConfig(s);return renderServerOverview(s);
}
function refreshServerHeader(live){const host=$('#server-live-status');if(host)host.innerHTML=statusBadge(live);}

async function renderServerOverview(s){const l=s.live||{},hist=await api(`/servers/${s.id}/history?hours=24`);$('#server-tab-view').innerHTML=`<div class="stats stats-5"><div class="stat"><span>Статус</span><b id="server-live-status">${statusBadge(l)}</b></div><div class="stat"><span>60s</span><b>${fmtHash(l.hash60s)}</b></div><div class="stat"><span>Базовая норма</span><b>${fmtHash(l.baselineHash)}</b><small>${l.baselineHash?`${l.baselineSamples||0} образцов`:`обучение ${l.baselineSamples||0}/${l.baselineMinSamples||12}`}</small></div><div class="stat"><span>CPU</span><b>${fmtTemp(l.tempC)}</b><small>${fmtMHz(l.cpuMHz)}</small></div><div class="stat"><span>Uptime XMRig</span><b>${fmtUptime(l.uptime)}</b></div></div><div class="grid2"><div class="panel chart-panel"><h2>Хешрейт</h2><canvas id="srv-hash"></canvas></div><div class="panel chart-panel"><h2>Температура CPU</h2><canvas id="srv-temp"></canvas></div></div>${l.grace?`<div class="notice">Grace period: сервис запускается, алерты и автовосстановление временно подавлены${l.graceRemaining?` ещё ~${Math.ceil(l.graceRemaining)} сек.`:''}.</div>`:''}`;charts.push(lineChart($('#srv-hash'),hist.map(x=>x.ts),hist.map(x=>x.hash60s),{label:'H/s',tick:v=>fmtHash(v),scale:hashrateScale(hist.map(x=>x.hash60s),l.baselineHash||l.hash60s)}));charts.push(lineChart($('#srv-temp'),hist.map(x=>x.ts),hist.map(x=>x.tempC),{label:'°C',tick:v=>`${Number(v).toLocaleString(undefined,{maximumFractionDigits:1})}°`,scale:temperatureScale(hist.map(x=>x.tempC))}));}
function lineChart(el,ts,data,{label,tick,scale={}}){return new Chart(el,{type:'line',data:{labels:ts.map(x=>new Date(x).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})),datasets:[{label,data,borderWidth:2,pointRadius:data.filter(Number.isFinite).length<3?3:0,pointHoverRadius:4,tension:.25}]},options:{responsive:true,maintainAspectRatio:false,interaction:{intersect:false,mode:'index'},plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{maxTicksLimit:8}},y:{beginAtZero:false,min:scale.min,max:scale.max,ticks:{stepSize:scale.stepSize,maxTicksLimit:6,callback:tick}}}}});}

async function renderServerPerformance(s){const l=s.live||{},profiles=await api('/profiles');$('#server-tab-view').innerHTML=`<div class="panel"><div class="panel-head"><div><h2>Профиль производительности</h2><span class="muted small">Текущий: ${esc(s.performanceProfile||'maximum')}. Перед изменением XMRig config автоматически резервируется.</span></div></div><div class="profile-grid">${profiles.map(p=>`<article class="profile-card ${s.performanceProfile===p.id?'selected':''}"><b>${esc(p.name)}</b><strong>${p.percent}%</strong><p>${esc(p.description)}</p><button class="${s.performanceProfile===p.id?'primary':'ghost'} profile-one" data-profile="${p.id}">${s.performanceProfile===p.id?'Применён':'Применить'}</button></article>`).join('')}</div></div><div class="stats"><div class="stat"><span>10s / 60s</span><b>${fmtHash(l.hash10s)}</b><small>${fmtHash(l.hash60s)}</small></div><div class="stat"><span>Базовая норма</span><b>${fmtHash(l.baselineHash)}</b><small>${l.baselineHash?`${l.baselineSamples||0} образцов`:`обучение ${l.baselineSamples||0}/${l.baselineMinSamples||12}`}</small></div><div class="stat"><span>CPU frequency</span><b>${fmtMHz(l.cpuMHz)}</b></div><div class="stat"><span>Load 1 / 5 / 15</span><b>${l.load1?.toFixed?.(1)??'—'}</b><small>${l.load5?.toFixed?.(1)??'—'} / ${l.load15?.toFixed?.(1)??'—'} · ${l.cpuCount||'?'} CPU threads</small></div></div><div class="panel"><h2>Детектор деградации</h2><p><b>Базовая норма</b> — автоматически изученный обычный хешрейт именно этого сервера. По умолчанию панель берёт успешные 60s-замеры за последние 24 часа, отбрасывает нижнюю нестабильную четверть и после минимум 12 замеров вычисляет устойчивое значение. Пока данных мало, показывается «обучение». Алерт создаётся, когда текущий 60s-хешрейт падает ниже нормы на заданный в настройках процент.</p><div class="meter"><span style="width:${l.baselineHash&&l.hash60s?Math.min(100,l.hash60s/l.baselineHash*100):0}%"></span></div><div class="muted small">Сейчас: ${fmtHash(l.hash60s)} · базовая норма: ${fmtHash(l.baselineHash)}</div></div>`;$$('.profile-one').forEach(b=>b.onclick=async()=>{if(!confirm('Применить профиль и перезапустить майнинг?'))return;try{await api(`/servers/${s.id}/actions/profile`,{method:'POST',body:{profile:b.dataset.profile}});toast('Профиль применён');await sleep(700);renderServer(s.id,'performance');}catch(e){toast(e.message,'error');}});}

function renderServerComponents(s){
  const l=s.live||{},m=l.monero||{},p=l.p2poolAnalytics||{},q=l.proxy||{},proxyRouted=['127.0.0.1:3334','localhost:3334','[::1]:3334'].includes(String(l.pool||'').trim());
  const pWorkers=(p.workers||[]).slice(0,20).map(w=>`<tr><td>${esc(w.name||w.address||'worker')}</td><td>${esc(w.address||'—')}</td><td>${fmtHash(Number(w.hashrate))}</td><td>${esc(String(w.uptime??'—'))}</td></tr>`).join('');
  const qWorkers=(q.workers||[]).slice(0,30).map(w=>`<tr><td>${esc(w.name||'worker')}</td><td>${esc(w.ip||'—')}</td><td>${fmtHash(Number(w.hashrate1m))}</td><td>${w.accepted??0} / ${w.rejected??0}</td></tr>`).join('');
  $('#server-tab-view').innerHTML=`
    <div class="component-cards component-cards-4">
      <article class="panel component-card"><div>${compBadge('XMRig',l.components?.xmrig)}</div><h2>⚒ XMRig ${helpIcon('Основной майнер. Показываются хешрейт, версия, shares и текущий pool.')}</h2><b>${fmtHash(l.hash60s)}</b><span>${esc(l.pool||'пул не определён')}</span></article>
      <article class="panel component-card"><div>${compBadge('p2pool',l.components?.p2pool)}</div><h2>🟠 P2Pool ${helpIcon('Децентрализованный пул Monero. Расширенная аналитика появляется при запуске p2pool с --data-api и --local-api.')}</h2><b>${p.available?fmtHash(Number(p.hashrate15m)):esc(l.p2poolStatus||'unknown')}</b><span>${p.available?`sidechain ${esc(p.sidechain)} · shares ${p.sharesFound??'—'}`:'Базовый статус доступен; Data API не обнаружен'}</span></article>
      <article class="panel component-card"><div>${compBadge('monerod',l.components?.monerod)}</div><h2>◉ Monero node ${helpIcon('Локальный monerod: синхронизация, peers, сложность сети и награда блока.')}</h2><b>${m.syncPercent!=null?`${Number(m.syncPercent).toFixed(2)}%`:'—'}</b><span>height ${m.height??'—'} / target ${m.targetHeight??m.height??'—'}</span></article>
      <article class="panel component-card"><div>${compBadge('Proxy',l.components?.xmrigProxy)}</div><h2>⇄ XMRig Proxy ${helpIcon('Прокси объединяет подключения майнеров и показывает отдельную статистику по workers и upstream-соединениям.')}</h2><b>${q.available?fmtHash(Number(q.hashrate?.[1]??q.hashrate?.[0])):(q.detected?'API недоступен':'не найден')}</b><span>${q.available?`${q.workerCount||0} workers · v${esc(q.version||'?')}`:'Автоопределение localhost API'}</span>${!q.detected?'<button id="install-xmrig-proxy" class="primary">⇄ Установить XMRig Proxy</button>':q.available&&!proxyRouted?'<button id="switch-xmrig-proxy" class="primary">⚡ Перевести XMRig на XMRig Proxy</button>':proxyRouted?'<button class="ghost" disabled>✓ XMRig уже через Proxy</button>':''}</article>
    </div>
    <div class="grid2">
      <div class="panel"><h2>🟠 P2Pool аналитика ${helpIcon('Локальный хешрейт P2Pool, shares, effort, miners и глобальные данные sidechain из встроенного Data API.')}</h2>
        ${p.available?`<div class="health-list"><div><span>Sidechain</span><b>${esc(p.sidechain||'main')}</b></div><div><span>15m / 1h / 24h</span><b>${fmtHash(Number(p.hashrate15m))} · ${fmtHash(Number(p.hashrate1h))} · ${fmtHash(Number(p.hashrate24h))}</b></div><div><span>Shares found / failed</span><b>${p.sharesFound??'—'} / ${p.sharesFailed??'—'}</b></div><div><span>Current / average effort</span><b>${p.currentEffort??'—'}% / ${p.averageEffort??'—'}%</b></div><div><span>Miner connections</span><b>${p.incomingConnections??p.workers?.length??'—'}</b></div><div><span>Pool hashrate</span><b>${fmtHash(Number(p.pool?.hashrate))}</b></div><div><span>Pool miners</span><b>${p.pool?.miners??'—'}</b></div><div><span>Blocks found</span><b>${p.pool?.totalBlocksFound??'—'}</b></div></div>`:`<div class="notice warn">Расширенная аналитика P2Pool пока недоступна. Панель может включить официальный Data API автоматически, сохранить изменение в автозапуске и перезапустить mining/p2pool service. <div class="button-row"><button id="enable-p2pool-analytics" class="primary">🟠 Включить P2Pool аналитику</button></div><span class="muted small">Перед изменением startup-файла создаётся backup; при неудачном перезапуске изменение откатывается.</span></div>`}
        ${pWorkers?`<div class="table-wrap compact-table"><table><thead><tr><th>Worker</th><th>Адрес</th><th>Hashrate</th><th>Uptime</th></tr></thead><tbody>${pWorkers}</tbody></table></div>`:''}
      </div>
      <div class="panel"><h2>⇄ XMRig Proxy ${helpIcon('Статистика берётся из локального HTTP API xmrig-proxy: summary и workers.')}</h2>
        ${q.available?`<div class="health-list"><div><span>Version / mode</span><b>${esc(q.version||'—')} / ${esc(q.mode||'—')}</b></div><div><span>Hashrate</span><b>${fmtHash(Number(q.hashrate?.[1]??q.hashrate?.[0]))}</b></div><div><span>Workers</span><b>${q.workerCount??q.workers?.length??0}</b></div><div><span>Miners now / max</span><b>${q.minersNow??0} / ${q.minersMax??0}</b></div><div><span>Accepted / rejected / invalid</span><b>${q.results?.accepted??0} / ${q.results?.rejected??0} / ${q.results?.invalid??0}</b></div><div><span>Upstreams active / total</span><b>${q.upstreams?.active??'—'} / ${q.upstreams?.total??'—'}</b></div></div>`:`<div class="empty">${q.detected?'xmrig-proxy найден, но localhost HTTP API недоступен.':'xmrig-proxy на сервере не обнаружен.'}</div>`}
        ${qWorkers?`<div class="table-wrap compact-table"><table><thead><tr><th>Worker</th><th>IP</th><th>1m</th><th>A/R</th></tr></thead><tbody>${qWorkers}</tbody></table></div>`:''}
      </div>
    </div>
    <div class="panel"><h2>◉ Синхронизация monerod ${helpIcon('Для оценки дохода панель также использует текущую network difficulty и награду последнего блока.')}</h2><div class="sync-line"><div class="meter"><span style="width:${Math.min(100,Number(m.syncPercent)||0)}%"></span></div><b>${m.synchronized?'Синхронизировано':m.syncPercent!=null?`${Number(m.syncPercent).toFixed(3)}%`:'Статус RPC недоступен'}</b></div><div class="form-grid read-grid"><div><span>Height</span><b>${m.height??'—'}</b></div><div><span>Target height</span><b>${m.targetHeight??'—'}</b></div><div><span>Inbound peers</span><b>${m.incoming??'—'}</b></div><div><span>Outbound peers</span><b>${m.outgoing??'—'}</b></div><div><span>Difficulty</span><b>${Number.isFinite(Number(m.difficulty))?Number(m.difficulty).toLocaleString():'—'}</b></div><div><span>Last block reward</span><b>${Number.isFinite(Number(m.blockRewardXmr))?Number(m.blockRewardXmr).toFixed(6)+' XMR':'—'}</b></div></div></div>`;
  const installProxy=$('#install-xmrig-proxy');
  if(installProxy)installProxy.onclick=async()=>{if(!confirm('Установить последний стабильный официальный XMRig Proxy?\\n\\nStratum: 0.0.0.0:3334\\nHTTP API: 127.0.0.1:60051\\nUpstream: из Настройки → Майнинг\\n\\nСуществующий XMRig автоматически переключён НЕ будет.'))return;try{installProxy.disabled=true;installProxy.textContent='Установка…';const r=await api(`/servers/${s.id}/actions/install-xmrig-proxy`,{method:'POST',body:{}});toast(`XMRig Proxy ${r.version} установлен`);await sleep(700);renderServer(s.id,'components');}catch(e){toast(e.message,'error');installProxy.disabled=false;installProxy.textContent='⇄ Установить XMRig Proxy';}};

  const switchProxy=$('#switch-xmrig-proxy');
  if(switchProxy)switchProxy.onclick=async()=>{if(!confirm('Перевести XMRig на XMRig Proxy?\\n\\nПанель сделает backup config.json, переключит pool на 127.0.0.1:3334 и перезапустит майнинг. Если хешрейт не восстановится, исходный config будет возвращён автоматически.\\n\\nОперация может занять 1–4 минуты.'))return;try{switchProxy.disabled=true;switchProxy.textContent='Переключение…';const r=await api(`/servers/${s.id}/actions/xmrig-to-proxy`,{method:'POST',body:{}});toast(r.alreadyConfigured?'XMRig уже использует XMRig Proxy':'XMRig переведён на XMRig Proxy');renderServer(s.id,'components');}catch(e){toast(e.message,'error');switchProxy.disabled=false;switchProxy.textContent='⚡ Перевести XMRig на XMRig Proxy';}};
  const enableP2pool=$('#enable-p2pool-analytics');
  if(enableP2pool)enableP2pool.onclick=async()=>{if(!confirm('Включить расширенную P2Pool аналитику автоматически?\\n\\nПанель добавит --data-api и --local-api в автозапуск P2Pool, сделает backup и перезапустит сервис. Майнинг может прерваться примерно на 1–2 минуты. При неудаче startup-файл будет восстановлен.'))return;try{enableP2pool.disabled=true;enableP2pool.textContent='Включение…';const r=await api(`/servers/${s.id}/actions/enable-p2pool-analytics`,{method:'POST',body:{}});toast(r.alreadyEnabled?'P2Pool аналитика уже включена':'P2Pool аналитика включена');await sleep(1200);renderServer(s.id,'components');}catch(e){toast(e.message,'error');enableP2pool.disabled=false;enableP2pool.textContent='🟠 Включить P2Pool аналитику';}};
}

function renderServerSystem(s){
  const l=s.live||{},hp=l.hugePages||{},d=s.discovery;
  $('#server-tab-view').innerHTML=`
    <div class="grid2">
      <div class="panel"><h2>Huge Pages</h2><div class="health-list">
        <div><span>Huge Pages (default size)</span><b>${hp.total??0} total / ${hp.free??0} free</b></div>
        <div><span>Размер</span><b>${hp.sizeKB?`${hp.sizeKB} KB`:'—'}</b></div>
        <div><span>1 GB pages</span><b>${hp.oneGTotal??0} total / ${hp.oneGFree??0} free</b></div>
        <div><span>XMRig allocation</span><b>${esc(String(l.hugepagesXMRig??'—'))}</b></div>
      </div><div class="control-block"><label>Количество 2 MB pages<input id="hp-2m-count" type="number" min="0" max="1048576" value="${hp.sizeKB===2048?(hp.total??0):0}"></label><button id="hp-2m-apply" class="ghost">Применить сейчас</button><label>Количество 1 GB pages<input id="hp-1g-count" type="number" min="0" max="1024" value="${hp.oneGTotal??5}"></label><button id="hp-1g-apply" class="ghost">Настроить при загрузке</button><span class="muted small">2 MB pages применяются через sysctl. 1 GB pages меняют GRUB и требуют перезагрузки.</span></div></div>
      <div class="panel"><h2>MSR и сеть</h2><div class="health-list">
        <div><span>MSR module</span><b>${l.msr?.module?'загружен':'не загружен'}</b></div>
        <div><span>/dev/cpu/0/msr</span><b>${l.msr?.device?'доступен':'нет'}</b></div>
        <div><span>DNS</span><b>${l.network?.dns===true?'OK':l.network?.dns===false?'FAIL':'—'}</b></div>
        <div><span>Internet</span><b>${l.network?.internet===true?'OK':l.network?.internet===false?'FAIL':'—'}</b></div>
      </div><div class="button-row"><button id="msr-on" class="ghost">MSR ON</button><button id="msr-off" class="danger-soft">MSR OFF</button></div></div>
    </div>
    <div class="panel"><div class="panel-head"><div><h2>Автоопределение и исправление</h2><span class="muted small">Панель сама ищет запущенный XMRig, config.json, systemd unit, p2pool и monerod. «Исправить автоматически» делает backup перед изменениями.</span></div><div class="button-row"><button id="discover" class="ghost">Автоопределить</button><button id="auto-fix" class="primary">Исправить автоматически</button></div></div>
      ${d?`<div class="discovery-grid"><div><span>CPU</span><b>${esc(d.hardware?.cpuModel||'—')}</b></div><div><span>OS</span><b>${esc(d.hardware?.os||'—')}</b></div><div><span>XMRig binary</span><code>${esc(d.xmrig?.binary||'—')}</code></div><div><span>config.json</span><code>${esc(d.xmrig?.config||s.xmrigConfigPath)}</code></div><div><span>XMRig service</span><code>${esc(d.xmrig?.service||s.xmrigService)}</code></div><div><span>NUMA</span><b>${d.hardware?.numaNodes??'—'}</b></div></div>`:'<div class="empty">Автоопределение ещё не выполнялось</div>'}
    </div>`;
  $('#discover').onclick=async()=>{try{toast('Ищу компоненты…');await api(`/servers/${s.id}/discover`,{method:'POST'});toast('Автоопределение завершено');renderServer(s.id,'system');}catch(e){toast(e.message,'error');}};
  $('#auto-fix').onclick=async()=>{if(!confirm('Панель проверит API XMRig, lm-sensors, Huge Pages/MSR в config и применит безопасные исправления с backup. Продолжить?'))return;try{const r=await api(`/servers/${s.id}/actions/auto-fix`,{method:'POST'});toast(r.fixes?.length?r.fixes.join(' · '):'Исправления не требуются');renderServer(s.id,'system');}catch(e){toast(e.message,'error');}};
  $('#hp-2m-apply').onclick=async()=>{const count=Number($('#hp-2m-count').value)||0;try{await api(`/servers/${s.id}/actions/hugepages`,{method:'POST',body:{mode:'2m',count}});toast('2 MB Huge Pages применены');setTimeout(()=>renderServer(s.id,'system'),800);}catch(e){toast(e.message,'error');}};
  $('#hp-1g-apply').onclick=async()=>{const count=Number($('#hp-1g-count').value)||0;if(!confirm(`Настроить ${count} × 1 GB Huge Pages в GRUB? Изменение вступит в силу после перезагрузки.`))return;try{const r=await api(`/servers/${s.id}/actions/hugepages`,{method:'POST',body:{mode:'1g',count}});toast(r.rebootRequired?'Huge Pages настроены. Требуется перезагрузка.':'Huge Pages настроены');}catch(e){toast(e.message,'error');}};
  $('#msr-on').onclick=async()=>{try{await api(`/servers/${s.id}/actions/msr`,{method:'POST',body:{enabled:true}});toast('MSR включён');setTimeout(()=>renderServer(s.id,'system'),1200);}catch(e){toast(e.message,'error');}};
  $('#msr-off').onclick=async()=>{if(!confirm('Отключить MSR для XMRig и перезапустить сервис?'))return;try{await api(`/servers/${s.id}/actions/msr`,{method:'POST',body:{enabled:false}});toast('MSR отключён');setTimeout(()=>renderServer(s.id,'system'),1200);}catch(e){toast(e.message,'error');}};
}

async function renderServerLogs(s){$('#server-tab-view').innerHTML=`<div class="log-tabs"><button class="ghost log-load active" data-kind="xmrig">XMRig</button><button class="ghost log-load" data-kind="p2pool">p2pool</button><button class="ghost log-load" data-kind="monerod">monerod</button></div><div class="panel"><pre id="component-log" class="log">Загрузка…</pre></div>`;const load=async kind=>{const out=$('#component-log');out.textContent='Загрузка…';try{out.textContent=await api(`/servers/${s.id}/logs/${kind}?lines=500`);}catch(e){out.textContent=e.message;}$$('.log-load').forEach(b=>b.classList.toggle('active',b.dataset.kind===kind));};$$('.log-load').forEach(b=>b.onclick=()=>load(b.dataset.kind));load('xmrig');}

function renderServerConfig(s){$('#server-tab-view').innerHTML=`<div class="grid2"><div class="panel"><h2>Быстрые действия</h2><div class="action-stack"><button id="cfg-restart" class="primary">Перезапустить майнинг</button><button id="cfg-apply" class="ghost">Применить глобальный XMRig config</button><button id="cfg-terminal" class="ghost">⌨ Открыть SSH-терминал</button><button id="cfg-edit" class="ghost">Редактировать сервер</button><button id="cfg-bootstrap" class="danger-soft">Bootstrap / переустановка</button></div></div><div class="panel"><h2>Произвольная SSH-команда</h2><p class="muted small">Для ручной настройки удобнее терминал. Это поле оставлено для одноразовых команд без интерактивного ввода.</p><textarea id="remote-command" rows="5" placeholder="systemctl status mining --no-pager"></textarea><button id="run-command" class="ghost">Выполнить</button><pre id="command-output" class="log small-log"></pre></div></div>`;$('#cfg-terminal').onclick=()=>openTerminal(s);$('#cfg-edit').onclick=()=>openServerForm(s);$('#cfg-restart').onclick=async()=>{try{await api(`/servers/${s.id}/actions/restart`,{method:'POST'});toast('Перезапуск запущен; действует grace period');}catch(e){toast(e.message,'error');}};$('#cfg-apply').onclick=async()=>{try{await api(`/servers/${s.id}/actions/apply-config`,{method:'POST'});toast('Конфиг применён');}catch(e){toast(e.message,'error');}};$('#cfg-bootstrap').onclick=()=>bootstrapModal(s);$('#run-command').onclick=async()=>{try{const r=await api(`/servers/${s.id}/actions/command`,{method:'POST',body:{command:$('#remote-command').value}});$('#command-output').textContent=`$ code=${r.code}\n${r.stdout}${r.stderr?`\n[stderr]\n${r.stderr}`:''}`;}catch(e){$('#command-output').textContent=e.message;}};}

  return { renderServer, refreshServerHeader };
}
