export function createSettingsPage(ctx) {
  const { $, $$, esc, fmtHash, fmtTemp, fmtMHz, fmtUptime, fmtDate, fmtUsd, fmtPct, sleep, api, toast, setHeader, navigate, openServerForm, bootstrapModal, openTerminal, bindCommonServerActions, statusBadge, compBadge, serverById, jobsPanel, Chart, hashrateScale, temperatureScale, charts, destroyCharts } = ctx;
  let overview = ctx.getOverview();
  let currentServerId = ctx.getCurrentServerId();
  let currentServerTab = ctx.getCurrentServerTab();
  const recalcSummary = () => ctx.recalcSummary();
  const loadOverview = async () => { const result = await ctx.loadOverview(); overview = ctx.getOverview(); return result; };

async function renderSettings(){const s=await api('/settings');setHeader('Настройки','Майнинг, автоматика, сеть и оповещения');$('#view').innerHTML=`<div class="settings-tabs"><button class="settings-tab active" data-st="mining">Майнинг</button><button class="settings-tab" data-st="automation">Автоматика</button><button class="settings-tab" data-st="system">Система</button><button class="settings-tab" data-st="notify">Оповещения</button></div><form id="settings-form" class="settings panel">
  <section data-settings="mining"><h2>Глобальный XMRig</h2><label>XMR-кошелёк<input name="wallet" value="${esc(s.wallet)}"></label><div class="form-grid"><label>Пул<input name="pool_url" value="${esc(s.pool_url)}"></label><label>Пароль пула<input name="pool_pass" value="${esc(s.pool_pass)}"></label><label>Версия XMRig для bootstrap<input name="xmrig_version" value="${esc(s.xmrig_version)}"></label><label>Профиль по умолчанию<select name="performance_profile_default"><option value="maximum" ${s.performance_profile_default==='maximum'?'selected':''}>Максимум</option><option value="balanced" ${s.performance_profile_default==='balanced'?'selected':''}>Баланс</option><option value="eco" ${s.performance_profile_default==='eco'?'selected':''}>Эко</option></select></label></div><div class="checks"><label><input name="pool_tls" type="checkbox" ${s.pool_tls==='1'?'checked':''}> TLS пула</label><label><input name="auto_apply_config" type="checkbox" ${s.auto_apply_config==='1'?'checked':''}> Автоприменение кошелька/пула</label></div><h2>Деградация</h2><div class="form-grid"><label>Падение от базовой нормы, %<input name="hash_drop_percent" type="number" value="${esc(s.hash_drop_percent)}"></label><label>Окно обучения, часов<input name="baseline_window_hours" type="number" value="${esc(s.baseline_window_hours)}"></label><label>Минимум замеров для обучения<input name="baseline_min_samples" type="number" value="${esc(s.baseline_min_samples)}"></label><label>Критическая температура, °C<input name="temp_critical" type="number" value="${esc(s.temp_critical)}"></label></div></section>
  <section data-settings="automation" class="hidden"><div class="setting-feature"><div><h2>Автовосстановление майнинга</h2><p>По умолчанию включено. После grace period панель ждёт несколько последовательных сбоев XMRig/нулевого хешрейта и только затем перезапускает указанный XMRig/mining systemd service. Между попытками действует cooldown, поэтому рестарт-цикл не создаётся.</p></div><label class="switch"><input name="auto_recovery_enabled" type="checkbox" ${s.auto_recovery_enabled==='1'?'checked':''}><span></span></label></div><div class="form-grid"><label>Неудачных проверок до restart<input name="auto_recovery_failures" type="number" min="1" value="${esc(s.auto_recovery_failures)}"></label><label>Cooldown, секунд<input name="auto_recovery_cooldown_seconds" type="number" min="60" value="${esc(s.auto_recovery_cooldown_seconds)}"></label><label>Grace period после старта, секунд<input name="grace_period_seconds" type="number" min="15" value="${esc(s.grace_period_seconds)}"></label><label>Offline alert после, секунд<input name="offline_after_seconds" type="number" min="15" value="${esc(s.offline_after_seconds)}"></label></div><div class="notice">Для твоей схемы <code>mining.service → monerod → sleep → p2pool → XMRig</code> рекомендуемый grace period — не меньше 60–90 секунд.</div></section>
  <section data-settings="system" class="hidden"><h2>Huge Pages / MSR</h2><div class="checks"><label><input name="huge_pages_enabled" type="checkbox" ${s.huge_pages_enabled==='1'?'checked':''}> Huge Pages в XMRig</label><label><input name="huge_pages_1g" type="checkbox" ${s.huge_pages_1g==='1'?'checked':''}> 1 GB Pages</label><label><input name="msr_enabled" type="checkbox" ${s.msr_enabled==='1'?'checked':''}> MSR</label></div><div class="form-grid"><label>Количество 1 GB Pages<input name="huge_pages_count" type="number" value="${esc(s.huge_pages_count)}"></label><label>Хранить историю, дней<input name="history_retention_days" type="number" value="${esc(s.history_retention_days)}"></label></div><h2>DNS / Internet</h2><div class="checks"><label><input name="network_check_enabled" type="checkbox" ${s.network_check_enabled==='1'?'checked':''}> Проверять сеть</label><label><input name="updates_auto_check" type="checkbox" ${s.updates_auto_check==='1'?'checked':''}> Автопроверка обновлений</label></div><div class="form-grid"><label>DNS host для проверки<input name="network_check_host" value="${esc(s.network_check_host)}"></label><label>Интервал обновлений, часов<input name="update_check_hours" type="number" value="${esc(s.update_check_hours)}"></label></div></section>
  <section data-settings="notify" class="hidden"><h2>Telegram</h2><div class="checks"><label><input name="telegram_enabled" type="checkbox" ${s.telegram_enabled==='1'?'checked':''}> Включить Telegram-уведомления</label></div><div class="form-grid"><label>Chat ID<input name="telegram_chat_id" value="${esc(s.telegram_chat_id)}"></label><label>Bot token<input name="telegram_bot_token" type="password" placeholder="${esc(s.telegram_bot_token||'не задан')}"></label><label>Cooldown алертов, секунд<input name="alert_cooldown_seconds" type="number" value="${esc(s.alert_cooldown_seconds)}"></label><label>Температура предупреждения, °C<input name="temp_warn" type="number" value="${esc(s.temp_warn)}"></label></div></section>
  <div class="save-row"><label><input id="apply-all" type="checkbox"> Сразу применить глобальный XMRig config ко всем серверам</label><button class="primary">Сохранить</button></div></form>`;
  $$('.settings-tab').forEach(b=>b.onclick=()=>{$$('.settings-tab').forEach(x=>x.classList.toggle('active',x===b));$$('[data-settings]').forEach(x=>x.classList.toggle('hidden',x.dataset.settings!==b.dataset.st));});
  $('#settings-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),settings={};for(const[k,v]of f.entries())settings[k]=v;for(const k of ['pool_tls','auto_apply_config','auto_recovery_enabled','huge_pages_enabled','huge_pages_1g','msr_enabled','network_check_enabled','updates_auto_check','telegram_enabled'])settings[k]=e.currentTarget.elements[k].checked?'1':'0';try{const r=await api('/settings',{method:'PUT',body:{settings,applyAll:$('#apply-all').checked}});const failed=r.applyResults?.filter(x=>!x.ok)||[];toast(failed.length?`Сохранено, ошибок применения: ${failed.length}`:'Настройки сохранены',failed.length?'error':'ok');}catch(err){toast(err.message,'error');}};
}

  return { renderSettings };
}
